#!/bin/bash
# Copyright (c) 2016 Fabian Schuiki
# Frontend for the potstill SCM generator.
BASE=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

if [ $# -eq 0 ]; then
	echo "usage: potstill -h"
	for f in $(find $BASE/commands -type f); do
		bn=${f#$BASE/commands/}
		echo "   or: potstill ${bn%%.*}"
	done
	for f in $(find $BASE/bin -type f); do
		bn=${f#$BASE/bin/}
		echo "   or: potstill ${bn%%.*}"
	done
	exit 1
fi

for DIR in "$BASE/commands" "$BASE/bin"; do
	CMD="$DIR/$1"
	if [ -e "$CMD" ]; then
		exec $CMD "${@:2}"
	fi
	if [ -e "$CMD.sh" ]; then
		exec bash -- "$CMD.sh" "${@:2}"
	fi
	if [ -e "$CMD.py" ]; then
		exec python3 "$CMD.py" "${@:2}"
	fi
done

exec "$BASE/potstill-core" "${@:1}"
