#!/bin/bash
# Copyright (c) 2016 Fabian Schuiki
# Frontend for the potstill SCM generator.
BASE=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

if [ $# -eq 0 ]; then
	echo "usage: potstill -h"
	for f in $(find $BASE/bin -type f); do
		echo "   or: potstill ${f#$BASE/bin/}"
	done
	exit 1
fi

CMD="$BASE/bin/$1"
if [ -e "$CMD" ]; then
	exec $CMD "${@:2}"
fi
if [ -e "$CMD.sh" ]; then
	exec bash -- "$CMD.sh" "${@:2}"
fi
if [ -e "$CMD.py" ]; then
	exec python3 "$CMD.py" "${@:2}"
fi

exec "$BASE/potstill-core" "${@:1}"
